### ISSUE TITLE
link rel=import type=css not using is="custom-style"

### ISSUE THREAD

**Issue by birkir** [Polymer/polymer-bundler#226]
When using the following import method:

``` html
<link rel="import" type="css" href="somefile.css">
```

Vulcanize injects the contents of that file using `<style>...</style>` but should be using:

``` html
<style is="custom-style">...</style>
```

At least in my case....

**Comment by birkir** [comment]
Don't know if you just want to import "regular stylesheet", you can just use the normal syntax. But https://github.com/Polymer/vulcanize/pull/227 solves it.

**Comment by azakus** [comment]
This is actually incorrect. `<style is="custom-style">` is only meant for main document styles, and styles inside of `dom-module` should be regular `<style>` tags.

**Comment by birkir** [comment]
Well they don't get parsed as such when Vulcanized. @apply and variables do not work. At least there should be a way to import a stylesheet via the custom-style attribute.

**Comment by garlicnation** [comment]
This should be fixed in the latest vulcanize release.
