### ISSUE TITLE
importHref error

### ISSUE THREAD

**Issue by TimWillis** [Polymer/polymer-bundler#240]
My page checks a users account and pulls down the correct account info, and changes content based on Url. I use this.importHref('component') to do this and works fine when not using vulcanize. I would like to be able to use this with vulcanize as my initial pay load has quite a few files, but with vulcanize now it throws: 
Uncaught NotSupportedError: Failed to execute 'registerElement' on 'Document': Registration failed for type 'dom-module'. A type with that name is already registered.

**Comment by ebidel** [comment]
This is because in your vulcanized bundles, you're loading polymer.html more than once.
To fix, you'll never to load polymer.html in your main page (and keep it out of the vulcanized bundles) or tell vulcanize not to inline polymer.html (and keep it as a `<link rel="import>`). For that, you can use `--exclude` or `--strip-exclude`.

**Comment by TimWillis** [comment]
Thanks Eric, that did get rid of that error, but I am still getting the
error for all the "composed" elements that I have in vulcanize and the
composed elements that I am dynamically importing.

Ex: I have in my vulcanized output the paper-item component. I also use
paper-item in my dynamically loaded components. This now throws the
following error:
Uncaught NotSupportedError: Failed to execute 'registerElement' on
'Document': Registration failed for type 'paper-item'. A type with that
name is already registered.

I have about 30 elements that are like this, It doesn't make sense for me
to strip them all out.

**Comment by azakus** [comment]
@garlicnation, probably a good use case for sharded vulcanize.

**Comment by ebidel** [comment]
Yea, we're working on a tool to handle vulcanized bundles much better. The error with paper-item is the same as the error you were seeing with polymer.html. The root case is that you cannot register an element twice. If you produce bundles s.t. that's the case, you'll get these types of errors. @garlicnation's tool will help.

**Comment by TimWillis** [comment]
Good, I am looking forward to the new tools. I just wish Polymer behaved
the same when using vulcanize and not using it. If I don't vulcanize,
Polymer ignores the second attempt to register an element. It would be cool
if, when using vulcanize, it would just throw a warning about the duplicate
registration and not break the app completely... I will check out
@garlicnation <https://github.com/garlicnation>'s tool to see if that is
what I need.

**Comment by garlicnation** [comment]
@TimWillis Check out https://www.npmjs.com/package/web-component-shards. It's still very rough, but it might help you out!

**Comment by azakus** [comment]
@TimWillis That's not Polymer behaving differently, just vulcanize breaking the deduplication property of HTML Imports by inlining.

With HTML Imports, all paths that resolve to the same absolute URL are deduplicated. When vulcanize inlines those imports, there is no longer a way to tell the imports system that some path has been loaded, and then the duplicate registrations happen.

**Comment by TimWillis** [comment]
@garlicnation <https://github.com/garlicnation> Awesome I will check it
out. Thanks

**Comment by TimWillis** [comment]
@azakus Thanks for the explanation. It would be cool if Vulcanize kept the paths in the vulcanized file and polymer or a script in the vulcanized file added the paths to the import system like adding a visited page with window.history.pushstate

**Comment by rsORAU** [comment]
What is then recommended when needing to ship all dependencies, including polymer.html, with the custom component?  If you can't include the Polymer definition in the built file, how are those developing projects not using Polymer supposed to implement the component?

**Comment by usergenic** [comment]
I'm going to close this issue and suggest that the https://github.com/Polymer/polymer-cli w/ https://github.com/Polymer/polymer-bundler now accounts for all the sharded aka multiple-bundle build scenarios described here.
