### ISSUE TITLE
Smart splitting of files

### ISSUE THREAD

**Issue by AndreasGalster** [Polymer/polymer-bundler#262]
I've watched the talk from polymer summit about performance patterns where it was mentioned to make html imports async or import them via javascript. Which gave me the idea that why would I want to load the entire vulcanized file at once? For example, the main layout of my page only needs certain standard elements such as drawers, icons, icon-buttons, neon-animations, etc. ... general elements. Then I have lots of elements like form elements or other custom elements that only are needed on a certain route. 

So I thought it would be great to split those elements apart in different import.html files and then vulcanize them seperately. Which in theory made sense but doesn't work since the same imports will have to be included in both files. Let's say I have two import.html files, one containing general elements, the second one contains form elements. Both of them will vulcanize some elements twice, which in effect results in not a smaller file size in total but a bigger one instead.

If I want to split imports to dynamically only load them when needed, vulcanize would need to know which imports aren't needed anymore in one of the conditionally loaded vulcanized imports.

I hope this makes sense as a feature request.

**Comment by garlicnation** [comment]
There are two problems you're facing: 1) Bundling of your HTML dependencies and 2) Lazy-loading.

Unfortunately, we don't yet have a solution for 2, but https://github.com/PolymerLabs/web-component-shards is a tool that leverages vulcanize to solve 1.

**Comment by AndreasGalster** [comment]
2) is really no issue that can be easily manually handled for a small app. Thanks, WCS looks like what I was looking for :)!

**Comment by justinfagnani** [comment]
This is very much the core part of the new bundler 2.0 design. Happily closing as fixed.
