### ISSUE TITLE
Vulcanize doesn't understand ES6 class-based declarations that use `beforeRegister` to set `is`

### ISSUE THREAD

**Issue by nicolasgarnier** [Polymer/polymer-bundler#263]
It seems that vulcanize is currently not correctly finding out the name (the `is` attribute) of the Polymer elements definition written as an ES6/ES2015 Class. When multiple elements definition as classes are present we get the following error/warning printed for each additional elements:

```
Ignoring duplicate element definition: undefined
```

Below is the minimal source file to replicate the issue:

**my-element.html**

``` html
<html>
<head>
  <link rel="import" href="bower_components/polymer/polymer.html">
</head>
<body>
<dom-module id="my-element">
  <template>
    <div>Hello World</div>
  </template>

</dom-module>
<script>
  class MyElement {
    beforeRegister() {
      this.is = 'my-element';
    }
  }
  Polymer(MyElement);

  class MyElement2 {
    beforeRegister() {
      this.is = 'my-element-2';
    }
  }
  Polymer(MyElement2);

  class MyElement3 {
    beforeRegister() {
      this.is = 'my-element-3';
    }
  }
  Polymer(MyElement3);
</script>
</body>
</html>
```

Then run `vulcanize my-element.html > /dev/null` and you'll get the following output on the console:

``` bash
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
```

**Comment by JosefJezek** [comment]
Please some solution...

@robdodson Could you help us?

**Comment by robdodson** [comment]
@ebidel have you run into this?

**Comment by ebidel** [comment]
Not specifically, but I always have to crisper, then babel. By the time
vulcanize sees the code it should be good to go.

**Comment by JosefJezek** [comment]
@ebidel Vulcanize tool write `Ignoring duplicate element definition: undefined` without     Babel before Vulcanize and also with Babel before Vulcanize.

**Comment by robdodson** [comment]
@JosefJezek as @ebidel mentioned, have you tried running the scripts through crisper to separate them out, then running the whole thing through vulcanize?

**Comment by ebidel** [comment]
@azakus this is something that vulcanize would need to support right?  That is, recognize:

```
beforeRegister() {
 this.is = 'my-element';
}
```

**Comment by azakus** [comment]
@ebidel this is probably a hydrolysis bug, pinging @garlicnation.

**Comment by JosefJezek** [comment]
@robdodson I have same issue with JS code excluded from element, check out the PSK+ https://github.com/StartPolymer/polymer-starter-kit-plus/blob/master/app/elements/my-greeting/my-greeting.html#L32

**Comment by dominik0711** [comment]
@JosefJezek @robdodson Any news on supporting ES2015 with Polymer Elements? My application also based on Polymer and ES2015. When I try to use a distributed version of my project the application didn't start up with an error in `elements.js: 5832` with the following error:

```
Uncaught TypeError: Cannot read property 'trim' of undefined
```
Is this error related to this vulcanize bug? Running my application in `development` mode everything is working properly.

**Comment by robdodson** [comment]
@dominik0711 It's hard to say. It may depend on how you're loading the elements. Are you just loading in 1 big vulcanized bundle or lazy loading multiple bundles? Are you running everything through Crisper before Vulcanize?

**Comment by dominik0711** [comment]
@robdodson My JS code is excluded from elements like @JosefJezek do. So there is no need to run the code through crisper, right? Or does crisper is doing more then separating JS Code from elements?

**Comment by robdodson** [comment]
@dominik0711 what do you mean when you say it's "excluded" from the elements?

**Comment by lastmjs** [comment]
It looks like the [issue I opened](https://github.com/Polymer/vulcanize/issues/362) may be similar. I also have most of my component scripts external, so each component has an HTML and a JS file. I need to vulcanize first so that all of my scripts are inlined, and then I'm going to use crisper to separate the files and run the JS file through the SystemJS builder. I'm doing all of this so that I can support TypeScript, async/await, es6 modules, and all of es6. I've got all of that working nicely in development, but the UI performance is horrible, so I really need to get vulcanize to handle TypeScript, async/await, and es6 modules. I would think that vulcanize would just need to read the external files and inline them, I'm not sure why it cares what's in the JS files. I know there is some form of analysis going on...but it would be nice if the analysis didn't stop the whole vulcanize process.

**Comment by mtsgrd** [comment]
@nicolasgarnier do you know anything new about this? I'm pretty keen to start building with Polymer 2.0(!)

**Comment by nicolasgarnier** [comment]
@mtsgrd Still not fixed apparently :) You can work around it since typically you'd need to transpile your ES6 code to ES5 with Babel.js to obtain large browser support. And ES5 code is not impacted.

**Comment by nicolasgarnier** [comment]
Still would have been nice to have this fixed for when we are developing and testing on Chrome without a Babel transpile step ;)

**Comment by robdodson** [comment]
@mtsgrd I wouldn't recommend building any production code on Polymer 2.0 just yet. It's still in a very early alpha stage. When it's released we'll be sure to have a build pipeline setup probably using Polymer CLI.

**Comment by mtsgrd** [comment]
@robdodson don't worry, I'm just eager to learn ahead of release. :)

**Comment by justinfagnani** [comment]
The new Bundler doesn't do this type of error checking, and the cew Analyzer/Linter doesn't have this particular bug.
