### ISSUE TITLE
How can we stop vulcanize to  verify external scripts path?

### ISSUE THREAD

**Issue by unbug** [Polymer/polymer-bundler#303]
In my case,some components is very sample,just a normal fragment with old html tags,I design them not just for Polymer and other web-components base projects,they can be in any projects.
Most of my project are pre-process,so vulcanize is the best solution for me,so I can keep all components html file and require them by `<link rel="import">`.
This maybe beyond what vulcanize do,I am just thinking about if I cant do some trick without hack the codes.
1. vulcanize verify all external scripts path,can we turn that off?I've try the `excludes` option,not working for me.
2. vulcanize replace all resources link,can we turn that off too?

**Comment by usergenic** [comment]
This should be addressed by the new polymer-analyzer based design of polymer-bundler.
