### ISSUE TITLE
Support vulcanizing a HTML import

### ISSUE THREAD

**Issue by AshleyScirra** [Polymer/polymer-bundler#326]
This is a feature request. Files to illustrate the suggestion: https://dl.dropboxusercontent.com/u/15217362/vulcimport.zip

Sometimes it's useful to vulcanize a HTML import instead of the main HTML document. For example if index.html imports main.html, which looks like this:

```
<script src="before.js"></script>
<script src="after.js"></script>
```

If you vulcanize main.html instead of index.html you end up with something like this:

```
<html><head><meta charset="UTF-8">
<script src="before.js"></script>
<script src="after.js"></script>
</head><body></body></html>
```

Since I vulcanized an import, the html, head, meta and body tags (and sometimes the hidden div element) are unnecessary. It should output something that also looks like a HTML import. This is useful with custom loaders, or if you want to partially vulcanize something. Perhaps it could be an option, e.g. `--as-import`?

**Comment by usergenic** [comment]
I think this is essentially handled in the way polymer-bundler bundles fragments and explicitly attempts to strip out the generated html, head and body elements which result from the parse5 AST.  Marking as closed.
