### ISSUE TITLE
Relative paths resolved with path.posix.relative lose characters on Windows.

### ISSUE THREAD

**Issue by njostonehouse** [Polymer/polymer-bundler#338]
When running vulcanize on Windows, I've noticed that relative paths are being resolved incorrectly. Characters are being lost, sometimes causing the build to fail, other times resulting in peculiar artifacts in the generated files.

For example, `tmp/shared.html` is in my project directory with the contents 

`<link rel="import" href="../../promise-polyfill/promise-polyfill-lite.html">`

And having installed [promise-polyfill](https://taylorhakes@github.com/taylorhakes/promise-polyfill.git) with bower, I try to vulcanize with the following script:

```
var Vulcan = require('vulcanize');
var hydrolysis = require('hydrolysis');

new Vulcan({
    fsResolver: new hydrolysis.FSResolver({
        attachAST: true,
        filter: function() {
            return false;
        },
        redirect: 'bower_components',
        root: "C:\\{project_folder}"
    }),
    inlineScripts: true,
    inlineCss: true,
    inputUrl: 'tmp/shared.html'
}).process();
```

I get the error
`ERROR finding C:\{project folder}\bower_components\romise-polyfill\Promise.js`

Note the missing `pr` from `promise-polyfill` folder name.

I believe this is caused when PathResolver uses path.posix.relative ([pathresolver.js](https://github.com/Polymer/vulcanize/blob/master/lib/pathresolver.js#L89)). To illustrate, using path.posix at the node command line:

`path.posix.relative('tmp', '../promise-polyfill/Promise.js')`

On Windows, results in

`'../../romise-polyfill/Promise.js'`

For some additional context, I found this while using [web-component-shards](https://github.com/PolymerLabs/web-component-shards).

**Comment by jonnenauha** [comment]
I had a similar bug in our linux build bot where the bower path was duplicated. This struct me as the failed file was the same.

```Cannot find file ../bower_components/bower_components/promise-polyfill/promise-polyfill-lite.html```

This was probably release .10 or .11 (which broken other things as well and gave numerous _flattenSomethingBehaviors is null warnings with the built app.html). I've reverted back to .8 for a working vulcanize. I was able to fix this duplicate bower_components in the path by defining `abspath : "./"` which might have again caused the flatten warnings...

Would hope there would be a bit more tests in this repo at least before pushing tags. Lots of build and *site* breaking changes. With grunt-vulcanize pulling in the latest its a bitch to override the dependency from your own npm packages.js.

I would recommend going back to .8 before they sort all this out, at least I know that works :)

**Comment by apalaniuk** [comment]
Unfortunately, the current web-component-shards (1.1.4) already uses vulcanize 1.14.8. Not wanting to go down the rabbit hole of mixing dependencies, it looks like you'd have to go back to v1.9.0, due to the changes in #196. There isn't a web-component-shards that has a vulcanize dependency that old.

A workaround exists for my workflow/project (reverting #196) but this would almost certainly cause issues for others.

**Comment by usergenic** [comment]
Going to close this issue and recommend use of https://github.com/Polymer/polymer-cli or https://github.com/Polymer/polymer-build w/ https://github.com/Polymer/polymer-bundler directly
