### ISSUE TITLE
[API] No output neither errors

### ISSUE THREAD

**Issue by vaurelios** [Polymer/polymer-bundler#348]
``` js
const gulp = require('gulp');
const jade = require('gulp-jade');
const vulcanize = require('gulp-vulcanize');

gulp.task('jade', function () {
    return gulp.src('./components/*.jade')
        .pipe(jade())
        .pipe(gulp.dest('build/compiled-jade'));
});

gulp.task('vulcanize', ['jade'], function () {
    return gulp.src('/build/compiled-jade/graduando-quest.html')
        .pipe(vulcanize({
            abspath: '.',
        }))
        .pipe(gulp.dest('build'));
});

gulp.task('default', ['vulcanize']);
```

the above `gulpfile.js` ends ok, no error but neither output file.

using vulcanize from command line in the same project works ok.

`vulcanize -p $PWD /build/compiled-jade/graduando-quest.html`

The gulp output:

```
[18:21:36] Using gulpfile ~/git/GraduandoQuest/gulpfile.js
[18:21:36] Starting 'jade'...
[18:21:37] Finished 'jade' after 305 ms
[18:21:37] Starting 'vulcanize'...
[18:21:37] Finished 'vulcanize' after 4.66 ms
[18:21:37] Starting 'default'...
[18:21:37] Finished 'default' after 21 μs
```

I posted on `gulp-vulcanize` issue tracker but him recommended to post here. sindresorhus/gulp-vulcanize#38

**Comment by nicholaswmin** [comment]
You're not loggging any errors in your pipeline.

Let this be an example:

```
  gulp.src('app/elements/elements.html')
    .pipe(vulcanize({
      stripComments: true,
      inlineCss: true,
      inlineScripts: true
    }))
    .on('error', gutil.log) // This is the important bit you're missing
    .pipe(gulp.dest('./dist/elements'));
```

You probably have errors in your elements and you're not logging the errors themselves.

**Comment by bereziuk** [comment]
+1
I had the same issue when imported component depends on older version of Polymer.
I removed this component and in my case it is solved but this error should be handled.

**Comment by usergenic** [comment]
Please upgrade to polymer-build + polymer-bundler instead of gulp-vulcanize!
