### ISSUE TITLE
lazy-loading vulcanized files

### ISSUE THREAD

**Issue by beta-vulgaris** [Polymer/polymer-bundler#361]
We're building a large, complex webapp. Currently we have index.html, which loads all the necessary content and which is the only page the browser accesses. (e.g. no <a href=... to other pages)
Due to the size of the application we would like to break the code into different sections and vulcanize and lazy-load them when needed (with this.importHref(...), e.g. when a specific section of the app is accessed).

My problem is now that any vulcanized resource in index.html clashes with the same vulcanized resource in a lazy-loaded section:

Failed to execute 'registerElement' on 'Document': Registration failed for type 'xxx'. A type with that name is already registered.

This means I'd have to exclude all the resources from app sections that were previously included in index.html.

Could we have the following in vulcanize:
1. Output all the imports gathered for a vulcanized file (so that you could exclude these in other vulcanized files).
2. Join the resources in a way that multiple loads don't break execution (just like multiple <link rel="import" will be ignored)

Number 2 would be fantastic to have!
E.g. if two sections of our app would use a specific webcomponent, we could vulcanize both sections with the webcomponent. This would prevent errors when accessing the sections one after the other and avoid having to vulcanize this webcomponent in a central file (e.g. index.html).
The implications of this are that we can defer loading to when it is needed and not push it to the landingpage.

**Comment by s-trooper** [comment]
i have exactly the same problem. larger app with need for lazy/dynamic load so vulcanize cannot be applied. i would appreciate if the 2. solution could be implemented.

**Comment by web-padawan** [comment]
For now, your choice is [web-component-shards](https://github.com/Collaborne/web-component-shards). Hope that in the near future sharding logic will be implemented in `v3`, see #373

**Comment by justinfagnani** [comment]
The best bet right now is to use the Polymer CLI, which produces sharded & bundled builds based on an entrypoint (index.html) / shell / fragments structure.

@web-padawan yes, we're building sharded bundling right into Vulcanize which will replace the sharding logic in the CLI. The Polymer CLI is going to be the supported command line interface going forward.

**Comment by s-trooper** [comment]
thank you for pointing me to the "Polymer CLI" project, it seems very interesting approach. But i am failed to create prototype of cli project for our app, in first place we use es6 and uglify don't support it. Anyway my impression is that "Polymer CLI" projects have to be build that very way from the beginning and need a extra work to get lazy loading working still ...

IMHO the solution (2) that vulcanized/bundled imports work with normal elements/imports would be way nicer/simpler.

**Comment by web-padawan** [comment]
@s-trooper have a look at https://github.com/web-padawan/pack
There you can find an example of using `web-component-shards` together with [app-router](https://github.com/erikringsmuth/app-router) and [iron-lazy-pages](https://github.com/TimvdLippe/iron-lazy-pages). Babel config is also implemented there.

In the future, I'll use [polymer-build](https://github.com/Polymer/polymer-build), which still lacks some config options (e. g. shared bundle name and location).

**Comment by raghav135** [comment]
+1

**Comment by daKmoR** [comment]
I guess shards won't work for many situations...

e.g. I have a user defined amount of pages (so dynamic) where every page can have various amount of Elements/HtmlImports

Example:
page1: import "special-text"
page2: import "special-text" && "special-image"
page3: import "special-text" & "special-image" & "special-magic"
pageX: ...
...
each special-* elements has an html import to polymer right at the top of the file.

Situation 1: no vulcanize
```
page1: 
+ import special-text
+ import polymer
=> many requests :/

switch to page2: (e.g. loading page2 via fetch and replace "content-area")
+ import special-image;
- skipped polymer (already been imported)

switch to page3:
+ import of special-magic; 
- skipped polymer (already been imported)
- skipped special-image (already been imported)
```

Situation 2: vulcanize
```
page1: 
+ import "vulcanize-page1.html" (vulcanize of "special-text, polymer")
=> super fast only 1 request

switch to page2:
+ import special-image
+ import special-text (url has not been imported so far)
+ import polymer and all of its sub componentes as the url "polymer" has not been imported so far
=> many "Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry"

switch to page3:
+ import special-magic
- skipped polymer (already been imported)
```


I guess a solutions would be something like this but I'm not sure howto implement and if it's even possible...
- inside the vulcanized version we would define all the files that have been imported als already loaded

e.g. inside vulcanize-page1.html
```
...
<link rel="import" href=".../special-text.html" already-loaded="true">
<dom-module id="special-text">
...
<link rel="import" href=".../special-image.html" already-loaded="true">
<dom-module id="special-image">
```

so the next time someone does
`<link rel="import" href=".../special-text.html">`
it will be ignored as it has been already loaded inside the vulcanized file

it could maybe something more complicated (psoido code) vulcanize-page1.html
```
<script>
  // create link rel="import" 
  // prevent loading
  // or manually add to import map (from W3C working draft) but I'm not sure if that can be manipulated
</script
```

so if anyone got any clues how to do this pls let me know :)

**Comment by justinfagnani** [comment]
@daKmoR we're going to make sure that the Bundler handler multi-page apps and just does the right thing.

**Comment by daKmoR** [comment]
@justinfagnani that would be awesome... any ideas on how to actually archive that?

for now I'm replacing my `<link rel="import" href="..">` imports with my "own tag" `<html-import if-tag-not-available="read-more" href="../path/read-more.html"></html-import>` that simply checks if that element is already defined before using Polymer.importHref().

```html
<dom-module id="html-import">
	<script>

		class HtmlImport extends Polymer.Element {

			static get is() { return 'html-import' }

			static get properties() {
				return {
					href: {
						type: String,
						reflectToAttribute: true
					},
					ifTagNotAvailable: {
						type: String,
						reflectToAttribute: true
					}
				};
			}

			constructor() {
				super();
			}

			ready() {
				super.ready();
				if (!window.customElements.get(this.ifTagNotAvailable)) {
					Polymer.importHref(this.href);
				}
			}

		}

		customElements.define(HtmlImport.is, HtmlImport);
	</script>
</dom-module>
```

**Comment by daKmoR** [comment]
Now release as an actual web component if anyone needs it
https://www.webcomponents.org/element/daKmoR/grain-html-import

**Comment by usergenic** [comment]
@daKmoR Have you tried out the new polymer cli / bundler?  Bundler is a nearly complete rebuild of vulcanize that is multi-page app aware and also supports lazy imports, which are akin to the Polymer.imporHref but are declarative and Bundler can reason about them in your project.  More here: https://github.com/Polymer/lazy-imports

**Comment by usergenic** [comment]
Marking this Issue as complete, because I *think* bundler combined with bundler manifest output does everything asked for here.  I'll do a writeup/blogpost perhaps.
