### ISSUE TITLE
How do I use the Bundler with TypeScript.

### ISSUE THREAD

**Issue by lastmjs** [Polymer/polymer-bundler#362]
Just from looking around issues and such, it looks like `--inline-scripts` is running the scripts through hydrolisis. Can we allow turning some features of hydrolysis' checking off? I don't think it is always desirable to enforce some features of the static analysis. Sometimes just placing the text of the script file without any modification is what is wanted.

For example:

I'm trying to use `vulcanize` to create one html file with all of my TypeScript files inlined (`<script src="my-component.ts"></script>` will be inlined). I then want to run that file through crisper to get a file that is the concatenation of my TypeScript files, which I will then run through the SystemJS builder to handle all of the TypeScript and ES6. But, I think uglify is ruining the inlining, because it doesn't understand TypeScript.

It looks like I'm having the same problem as in [this issue](https://github.com/Polymer/vulcanize/issues/139), but the API has changed now, and I don't think the solution presented there works anymore. [This issue](https://github.com/Polymer/vulcanize/issues/263) also looks relevant.

**Comment by lastmjs** [comment]
It looks like I'm having the same problem as in [this issue](https://github.com/Polymer/vulcanize/issues/139), but the API has changed now, and I don't think the solution presented there works anymore.

**Comment by justinfagnani** [comment]
@lastmjs I'm scrubbing old issues, is this still relevant for you?

I think the solution here is to give your scripts a type so that they're not assumed to be JavaScript. I'm not sure what the mime-type of TypeScript is, but maybe `application/x-typescript`. At some point you need a tool to rewrite your `.ts` URLs to `.js`.

**Comment by lastmjs** [comment]
That sounds like a good idea. I think we can close this, I've moved on to other ways of achieving what I wanted, but this will be a good place to pick up if I ever come back to it.
