### ISSUE TITLE
omitting --inline-scripts adds src= to <script> AND inlines

### ISSUE THREAD

**Issue by danbeam** [Polymer/polymer-bundler#364]
repro steps and version:

``` shell
$ echo 'alert(1)' > blah.js
$ echo '<script src="blah.js"></script>' > blah.html
$ vulcanize blah.html 
<html><head><meta charset="UTF-8"><script src="blah.js">alert(1)
</script>
</head><body></body></html>
$ vulcanize --version
vulcanize: 1.14.8
```

note both the `src="blah.js"` **and** the inlined `alert(1)`.

as far as i can tell:

``` js
args.inlineScripts = args['inline-scripts'];
args.inlineCss = args['inline-css'];
```

in [`bin/vulcanize`](https://github.com/Polymer/vulcanize/blob/master/bin/vulcanize#L126-L127) are both `false` and

```
this.enableCssInlining = Boolean(opts.inlineCss);
this.enableScriptInlining = Boolean(opts.inlineScripts);
```

in [`lib/vulcan.js`](https://github.com/Polymer/vulcanize/blob/master/lib/vulcan.js#L94-L95) are also `false` when `--inline-css` and `--inline-scripts` are omitted, and neither of [these branches](https://github.com/Polymer/vulcanize/blob/master/lib/vulcan.js#L450-L459) seem to be hit:

``` js
if (this.enableScriptInlining) {                                                                                                    
  chain = chain.then(function(docObj) {
    return this.inlineScripts(docObj.doc, docObj.href);
  }.bind(this));
}
if (this.enableCssInlining) {
  chain = chain.then(function(docObj) {
    return this.inlineCss(docObj.doc, docObj.href);
  }.bind(this));
}
```

i be like: ¯\_(ツ)_/¯

/cc @azakus @garlicnation @tgsergeant

**Comment by usergenic** [comment]
Closing this issue because I'm pretty sure vulcanize honors these now and polymer-bundler does too.
