### ISSUE TITLE
Add ability to split components into bundles declaratively

### ISSUE THREAD

**Issue by nicholaswmin** [Polymer/polymer-bundler#367]
Would be nice to have a way to split the vulcanized bundle into different ones
## A use case:

I want to use a component in 2 pages but not in a 3rd 
I'd like to keep things light and include in the 3rd page only the elements it needs
### Something like this would be ideal:

In `elements.html` configure each inclusion like so:

```
<link rel="import" href="aux-button/aux-button.html" pages="index, contact">
<link rel="import" href="aux-button/side-panel.html" pages="contact">
```

with the `page` property taking a string of comma-separated strings of bundles that include that component

And it would spit out:
- `elements-index.html` (includes `aux-button`, `slide-panel`)
- `elements-contact.html` (includes just `slide-panel`)

Surely a gulp-task can be used for each "bundle" but it just would make things messy _fast_

**Comment by usergenic** [comment]
One year later...

Declaratively expressing bundles with an attribute on the link itself is a potentially useful idea but I think it would be prone to error as dependencies change, whereas explicit imports in a dependent file wouldn't be.

If you either choose to not use a "shared bundle" strategy or configure shared/shell strategies to require a higher minimum number of entrypoint dependents before being merged into the shared bundle or shell, the default behavior will be to produce bundles which contain only the actual eagerly imported transitive dependencies required for a given entrypoint.

However, I get the ergonomic value of what you're trying to achieve-- you want to author your templates by doing an explicit import only of `elements.html` everwhere and then have it split accordingly based on what is needed on a given page.  That said, this is probably a behavior better achieved by automatic analysis than hand grouping, if possible.

If bundler had access to a reliable package usage dependency analysis, it would be able to split things accordingly.  That said, bundler has no support for the kind of "splitting" implied by this at this point, so marking as closed for now.

**Comment by nicholaswmin** [comment]
[Fragments][1] have solved my problem to the T.

[1]: https://www.polymer-project.org/2.0/docs/tools/polymer-json#fragments
