### ISSUE TITLE
--inline-scripts breaks valid code

### ISSUE THREAD

**Issue by gelraen** [Polymer/polymer-bundler#378]
`vulcanize --inline-scripts` replaces `for(g=d+e;g-->d;)` with `for(g=d+e;g--\x3ed;)`, which results in parse error.

Encountered while trying to use https://github.com/OpenKieler/klayjs/blob/master/klay.js - Java library compiled with GWT.

**Comment by arturparkhisenko** [comment]
duplicate of https://github.com/Polymer/polymer-bundler/issues/304

**Comment by justinfagnani** [comment]
Thanks for pointing that out @arturparkhisenko Closed as duplicate. @gelraen you may want to subscribe to #304
