### ISSUE TITLE
Everything (even markup) ends up in hidden div

### ISSUE THREAD

**Issue by mikaelharsjo** [Polymer/polymer-bundler#412]
## Given this input html
```html
<html>
  <body>
    <h1>Test</h1>
  </body>
</html>
```

`polymer-builder index.html`

produces
```html
<html><head></head><body><div hidden="" by-polymer-bundler="">

    <h1>Test</h1>


</div></body></html>
```

while `vulcanize index.html` used to produce 

```html
<html><head><meta charset="UTF-8"></head><body>
    <h1>Test</h1>
  

</body></html>
```

The content is then ofc not visible because of style sheet.
Tested with  `v2.0.0-pre.1` and `1.14.12`

**Comment by usergenic** [comment]
So this issue is fixed.  There's a related issue #415 that's addressed in #416 but the problem described was fixed in #414.
