### ISSUE TITLE
js file vulcanized multiple times

### ISSUE THREAD

**Issue by beta-vulgaris** [Polymer/polymer-bundler#417]
In my project we gather all resources we use in an imports file, which we then vulcanize. These resources are mainly polymer webcomponents. Some of these polymer webcomponents use a js library we wrote, containing various helper functions. Now I notice that the vulcanized imports file has this js file vulcanized multiple times!

My questions are now:
- Does vulcanize only prevent multiple imports of the same file for html? What about js, css, ...?
- How does vulcanize avoid multiple imports of polymer webcomponents?
- Is there anything I can do to fix this? (e.g. pass certain parameters to polymer-bundler)

**Comment by web-padawan** [comment]
AFAIK only HTML imports are de-duped, not script tags. 
So, create one file where script is included, then import this file in each of required locations.
Also, consider placed shared helpers into `behaviors` and combine them where needed.

**Comment by beta-vulgaris** [comment]
I "wrapped" the .js library in an HTML import and now it is only included once in the vulcanized file.
So yes, it seems only HTML imports are de-duped!
It would be great if in the future .js/.css/... imports would be de-duped.

**Comment by beta-vulgaris** [comment]
I just noticed that "stripExclude" is also only effective for html imports and not .js... please fix or at least document this!

**Comment by web-padawan** [comment]
> It would be great if in the future .js/.css/... imports would be de-duped.
This is not how browser works, at least for script tags.
If you can defer loading some stuff, consider using [polymer-lib-loader](https://github.com/LasaleFamine/polymer-lib-loader) for such libraries. 
E. g. you possibly don't need libraries like `d3` or `moment` on app startup, so you can load them asynchrounously to decrease size of common bundle. This is a good approach if you follow `app-shell` pattern.

**Comment by justinfagnani** [comment]
The Bundler can't de-dupe script tags, at least until `<script type=module>`, because like @web-padawan noted, that's not how the browser behaves. The Bundler tries to be as transparent as possible.
