### ISSUE TITLE
polymer-build breaks if the project path has spaces

### ISSUE THREAD

**Issue by FredKSchott** [Polymer/polymer-bundler#419]
See:
-  https://github.com/Polymer/polymer-build/issues/102
- https://github.com/Polymer/polymer-build/issues/102#issuecomment-271387412
- https://github.com/Polymer/polymer-build/issues/102#issuecomment-276530616

Seems to be caused by hydrolysis, or some interaction between hydrolysis and vulcanize. We should add a test for this as well so that we know its fixed in the new polymer-bundler.

/cc @usergenic

**Comment by usergenic** [comment]
I hope this will have been fixed by #439 and also tested behavior in 3cadda16f76ed64638374291cfaa0585023cc72c

**Comment by usergenic** [comment]
Closing this and will watch issue in Polymer/polymer-build instead since Bundler tests for spaces.
