### ISSUE TITLE
Bundling and SEO

### ISSUE THREAD

**Issue by hakanyildiz** [Polymer/polymer-bundler#426]
I had vulcanized all polymer and my custom elements. When I look my vulcanized.html file, I see that my file includes 70.000 rows and then I tested my page speed in https://testmysite.thinkwithgoogle.com/. 
Our result is attached. Is this effect our SEO? 
![fskafklafalfsklak](https://cloud.githubusercontent.com/assets/5807835/22728322/f91a477a-ede5-11e6-8d0c-eaf44e5aa4f7.png)

**Comment by abdonrd** [comment]
Nop. 😕 

I also use vulcanize (now polymer-bundler) and I get a better score:

<img width="1182" alt="screen shot 2017-02-08 at 09 15 29" src="https://cloud.githubusercontent.com/assets/1007051/22728624/4df09940-eddf-11e6-8e94-a1ec92783c60.png">

**Comment by rictic** [comment]
What did you lose points on? How big is your site on the wire (look in the network panel of your browser's devtools)

**Comment by usergenic** [comment]
This is very old question pending response from original asker, so marking closed.  Reopen if this continues to be concern.
