### ISSUE TITLE
Place shared_bundle_XX.html files at the right level and allow configuring it

### ISSUE THREAD

**Issue by web-padawan** [Polymer/polymer-bundler#437]
Today I tweaked `bundle.js` in my installed `polymer-build` module and started to play with `minEntrypoints` option to test how it works.

Here is the issue I faced: now, my shared bundles include paths like `src/components/app/my-app/my-app.html`, while real path to shell will be just `components/app/my-app/my-app.html`.

In short, it would be nice to have `shared_bundle_1.html` and others (actually I have 20 shared bundles for `minEntrypoints` = 3) placed into the separate directory rather than project root.

The reason is my app architecture: I believe that placing `bower_components` inside of the `src` is not a good idea and so I do some tricks. 

1. `index.html` is located inside of the `src` directory, while `bower_components` dir is outside:

```
root/
|
|--src/
|    |--components/
|    |--images/
|    |--index.html
`--bower_components/
```

2. For production, I have slightly different structure:
```
root/
|
|--components/
|--images/
|--bower_components/
`--index.html
```
 
3. To make this work, after bundling I use the following copy task to put them into `dist`:

```
function copyVulcanized () {
    return gulp.src([
       VULCANIZE_CACHE + '/src/components/app/**/*-app.html',
       VULCANIZE_CACHE + '/src/components/pages/**/*-page.html'
    ], { base: VULCANIZE_CACHE + '/src' })
    .pipe(gulp.dest(GULP_CACHE))
    .pipe($.size({
        title: 'vulcanize'
    }));
```
Those files listed via globs are shell and fragments (as of now, bundled build also contains lots of other stuff, see [this issue](https://github.com/Polymer/polymer-build/issues/70)).

In order to have shared bundles working, I need to rewrite paths somehow, because shell links, as well as `assetpath` attributes (and maybe other rewritten stuff too), are pointing to the `src` directory, which does not exist in production build.

But placing shared bundles in the right place would end up with relative paths like `../../my-app/my-app.html`, which is exactly what I want to reach.

What about making directory for shared bundles configurable? @usergenic WDYT?

/cc @FredKSchott as this path for shared bundles should be passed as some option from `polymer-project-config`, as well as `minEntrypoints` number.

**Comment by justinfagnani** [comment]
@web-padawan we don't actually recommend putting `bower_components` inside `src/` in any of our templates, so your source setup isn't very odd, except for maybe `index.html` being inside `src/. We may or may not need to shore up options around the entrypoint file to make that work in all tools, but it should be ok.

However, I'd _really_ recommend against changing the layout of your files between development and production. The main reason is that if relative paths change like that, then tools are going to not be able to find files in one of the two environments, and you'll need many fragile fixups of your source to change paths from development to production.

For instance, `index.html` would have paths like `./components/my-app.html` in development that would need to change to `/components/my-app.html` in production. Or if you choose to use production paths, then tools like the bundler and linter won't find the files.

If you just keep your development layout at production, you can avoid all that work. 

Is there a reason why you can't do a layout like:

```
root/
|--index.html
|--src/
|    |--components/
|    |--images/
`--bower_components/
```

**Comment by web-padawan** [comment]
Well, now when you're back from vacation I'm going to clarify my reasoning here.
You are totally right about keeping development layout in production. 
I wasted some time when dancing with `assetpath` RegEx etc. 

In fact, the only reason is that we are using docker and no one had provided a setup for Polymer projects by the time when I started migrating the project I'm working on from Polymer 0.5

So, we actually mount some directories from the host machine to container, and for production, our `dockerfile` looks like this: 
```
FROM nginx:1.11.0-alpine

COPY dist/ /var/www/my-app/
COPY nginx/ /etc/nginx/
```
And for development we just mount another directory, which looks like this:
```yaml
        volumes:
        - ./src/:/var/www/my-app/
        - ./vendor/:/var/www/my-app/vendor/
        - ./nginx/:/etc/nginx/
```
Atually I'm not sure about how to rewrite it better, because I'm not really want to mount project root directory too, and for sure I need to keep existing folder structure, without rewriting any imports.

BTW, there was a question in Slack about official docker image recently. And I think this might be useful to have one in the future.

**Comment by web-padawan** [comment]
What if we just place shared bundles at the same level as `shell` is located? That would be quite enough.
IMO, this also makes sense because users might want to process bundles at some point and globs like `components/my-app/**/*` would be fine in this case.

**Comment by usergenic** [comment]
This should be easy enough when https://github.com/Polymer/polymer-bundler/issues/483 and https://github.com/Polymer/polymer-build/pull/189 both land.

**Comment by usergenic** [comment]
Here's how you can do this with the new stuff (on master - about to release)

```js
const {generateCountingSharedBundleUrlMapper} = require('polymer-bundler');

mergeStream(project.sources(), project.dependencies())
    .pipe(project.bundler({
      // This mapper generates shared bundle files at:
      // `path/to/shared/bundle_1.html`, `path/to/shared/bundle_2.html`
      urlMapper: generateCountingSharedBundleUrlMapper('path/to/shared/bundle_')
    });
```

**Comment by usergenic** [comment]
If this won't solve for your issue, please re-open

**Comment by web-padawan** [comment]
This works fine, thanks! 👍  
Just decreased gzipped shell size from 291 Kb to 166 Kb, thanks to excluding large imports like `ace` and `d3` and placing them to separate bundles.
Actually I have 45 bundles with following snippet:
```
        .pipe(project.bundler({
            strategy: bundler.generateShellMergeStrategy(polymerJSON.shell, 4),
            urlMapper: bundler.generateCountingSharedBundleUrlMapper('src/components/shards/bundle-')
        }))
```
