### ISSUE TITLE
Make template URL fixup compatible with HTMLImports polyfill

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer-bundler#441]
The HTMLImports polyfill [has changed](https://github.com/webcomponents/html-imports/pull/38) how urls are re-written inside template elements and the bundler should do the same fix ups.

Now the polyfill only re-write url's inside templates that are (1) in the text of `<style>` elements or (2) in the `src` or `style` attributes of any element. 

This corresponds better to user expectations as these are inline loaded resources. It avoids, for example, re-writing url's in `href` attributes like `<a href>` which has been [an issue](https://github.com/Polymer/polymer/issues/4213) for Polymer users.

**Comment by sorvell** [comment]
Let's hold off on this change for now. We need to figure out how Polymer's hybrid mode works with this before proceeding.

**Comment by justinfagnani** [comment]
@sorvell, @kevinpschaaf, @usergenic and @valdrinkoshi what's the status of the URL rewriting changes? Do we have documentation on what rewriting is done, and what URL-related properties are available now?

**Comment by kevinpschaaf** [comment]
There are docs in the migration guide [here](https://www.polymer-project.org/2.0/docs/upgrade#urls-in-templates).  Basically, now only URL's in CSS are rewritten to be relative to the import (e.g. `@import ...`, `background: url(...)`, etc.); **nothing else** (including e.g. `src`, `href` attributes) is ever rewritten now, and user should use `[[rootPath]]` or `[[importPath]]` bindings to determine what template paths are relative to.

@arthurevans Would it make sense to add a proper (non-migration-related) section re: paths in templates to [this page](https://www.polymer-project.org/2.0/docs/devguide/dom-template)?

The ability to do hybrid `[[rootPath]]` and `[[importPath]]` bindings was back-ported to 1.x in https://github.com/Polymer/polymer/pull/4373, but looks like we still need to make a `1.9` release to make that available. cc/ @azakus @sorvell to make sure we don't loose track of that.

**Comment by usergenic** [comment]
To avoid surprising behaviors, this will be implemented as a global option to the bundler: `rewriteUrlAttrs` which will default to `false`.

**Comment by usergenic** [comment]
@kevinpschaaf Just confirming-- does the polyfill still rewrites urls in elements' style attributes?

**Comment by usergenic** [comment]
@sorvell I'm trying to get the bundler to mirror the expected behavior of the html imports polyfill wrt url rewriting in css, but I can't tell if this decision is settled.

Bundler will continue to rewrite urls inside `<style>...</style>` tags but can you tell me if urls should be rewritten in element `<div style="...">` attributes?

**Comment by valdrinkoshi** [comment]
FWIW `HTMLImports` polyfill doesn't rewrite urls in inline styles, only inside `<style>` elements and `href/src` attributes of `<link>, <script>` https://github.com/webcomponents/html-imports/blob/master/src/html-imports.js#L42

**Comment by usergenic** [comment]
@valdrinkoshi thank you.
