### ISSUE TITLE
Update README for Bundler 2.0

### ISSUE THREAD

**Issue by usergenic** [Polymer/polymer-bundler#445]
Probably need to rewrite it, especially because of bundling strategies etc.

**Comment by justinfagnani** [comment]
@usergenic I have a bunch of writing to do next week, I can add this to the list. If I get in a non-code flow I can probably get through it quickly.

**Comment by usergenic** [comment]
I did rewrite a lot of the README already, and its much better than when I created the issue, and if I don't close this now it will just keep staring at me and making me feel bad until the README is perfect which it won't be.
