### ISSUE TITLE
uri starting with "/" doesn't seem to be recognized.

### ISSUE THREAD

**Issue by hansanghoon** [Polymer/polymer-bundler#452]
Reproduce step.

1. create sample polymer app with polymer-cli : `polymer init` and enter enter enter.. done.
2. run `polymer-bundler index.html`
3. almost nothing happened to the output.
4. `index.html` is referencing its resources starting with "/" by default. change all of them to start without "/". i.e. `<link rel="import" href="/src/test02-app/test02-app.html">` --> `<link rel="import" href="src/test02-app/test02-app.html">`
5. `polymer-bundler index.html` now works as expected.

Is there any option for this situation?

**Comment by usergenic** [comment]
Thanks for the bug report.  There's a couple things:

1. It's a bug in the current `polymer-bundler` bin-- The default behavior should be to treat the current director as the project root.  I've fixed the behavior in  https://github.com/Polymer/polymer-bundler/pull/460
2. It is recommended to use `polymer build --bundle` as we may not release polymer-bundler with its own CLI.  (polymer-bundler is in pre-release mode right now)  See https://www.polymer-project.org/2.0/docs/tools/polymer-cli#bundles for more about `polymer-cli`

**Comment by usergenic** [comment]
The fix has been merged in.  Will go out in the 2.0.0-pre.12 release.
