### ISSUE TITLE
Bundler may have issues with windows paths OR non utf8 file encodings AND/OR inlining mixed encodings

### ISSUE THREAD

**Issue by usergenic** [Polymer/polymer-bundler#454]
From `#tools` slack channel:

`colin-krumware`
`@justin` in the file map, prior to piping to the bundler, the string encoding of some of my source files have a different string encoding than others

 ```const bundledBuildStream = forkStream(buildStream)
          .on('end', function(){ console.log(polymerProject.bundler); })
          .pipe(polymerProject.bundler)
          .on('end', function(){ console.log(polymerProject.bundler); })
          .pipe(gulp.dest(buildDirectory + '/bundled'));
```

looks like it wont match the fragment's encoded string

`'F:/Code/xx-polymer-stable/xx-polymer/src/stage/bower_components/xx-app/xx-imports.html' => <File "bower_components\xx-app\xx-imports.html" <Buffer 3c...` 

here is the fragment in the bundler (not the polymer config) `fragments: [ 'F:\\Code\\xx-polymer-stable\\xx-polymer\\src\\stage\\bower_components\\xx-app\\xx-imports.html' ],` 

that's in BuildBundler's file map, the analyzer's map looks ok. 

the shell file shows up with this encoding `'F:\\Code\\xx-polymer-stable\\xx-polymer\\src\\stage\\bower_components\\xx-app\\xx-app.html' => <File "bower_components\xx-app\xx-app.html" <Buffer 3c`

I think it may be worth mentioning that this is being run on a windows machine

**Comment by krumware** [comment]
I wanted to confirm that building with the same project config and gulpfile which did not work in windows DID work when building in a docker container, hopefully providing some indication that this may be related to windows paths

**Comment by usergenic** [comment]
It looks like this is not a Bundler issue at all.  Fix is in Build: see https://github.com/Polymer/polymer-build/pull/158

**Comment by usergenic** [comment]
@krumware, have an updated fix https://github.com/Polymer/polymer-build/pull/161 in review.

**Comment by krumware** [comment]
Thanks @usergenic!

**Comment by usergenic** [comment]
@krumware - latest polymer-cli / polymer-build releases include fix.  please let us know if you continue to have issues on Windows.

**Comment by krumware** [comment]
Thanks guys! Will text when I get back into the office
