### ISSUE TITLE
CSS @import rule URLs in imported HTML files are incorrect

### ISSUE THREAD

**Issue by emanguy** [Polymer/polymer-bundler#462]
I'm importing an HTML file in my main document which defines a custom element called "main-page". Polymer-Bundler is renaming a url in a @import statement incorrectly from `url("shared-styles/shared-styles.css")` to `url("main-page/shared-styles/shared-styles.css")`.

The reason this is incorrect is because this operates on the URL and not the file system itself. Because the element appears in the main document ("my-domain.com/folder/index.html") and not the imported document ("my-domain.com/folder/main-page/main-page.html"), the url is relative to the index document in the un-bundled version and therefore should still be `url("shared-styles/shared-styles.css")`.

**Comment by usergenic** [comment]
Just want to be visually explicit about what your setup is, to make sure I've got it right.

```html
<!-- my-domain.com/folder/index.html -->
<link rel="import" href="main-page/main-page.html">
<main-page></main-page>
```

```html
<!-- my-domain.com/folder/main-page/main-page.html -->
<dom-module id="main-page">
  <template>
    <style>
      @import url("shared-styles/shared-styles.css");
    </style>
  </template>
</dom-module>
```

The way I read the [html imports polyfill source](https://github.com/webcomponents/html-imports/blob/master/src/html-imports.js#L39), the `@import url()` is adjusted on import.  For this reason, you should adjust the `@import` statement in your `main-page.html` accordingly:

```html
<!-- my-domain.com/folder/main-page/main-page.html -->
<dom-module id="main-page">
  <template>
    <style>
      @import url("../shared-styles/shared-styles.css");
    </style>
  </template>
</dom-module>
```

Does this make sense?

**Comment by emanguy** [comment]
Yeah, that's what I did to combat the issue. Now I just can't serve the unbundled version but that's no big deal.

**Comment by usergenic** [comment]
side note: styles in `@import` aren't properly scoped by the polyfill, so "the polymer way" is to use `<style includes="name-of-shared-style-dom-module">` -- Please see https://www.polymer-project.org/1.0/docs/devguide/styling#style-modules
