### ISSUE TITLE
Assetpath doesn't get prepended for src attribute (now in shared bundles only)

### ISSUE THREAD

**Issue by web-padawan** [Polymer/polymer-bundler#501]
I upgraded our project to `polymer-build` 1.2.1 and noticed the same issue as #430. 
Now this only seems to happen when element gets placed to `shared-bundle-XX` file.

I reproduced this in my [sandbox](https://github.com/web-padawan/polymer-sandbox/tree/shared-bundle-assetpath), steps to reproduce:

1. `git clone https://github.com/web-padawan/polymer-sandbox`
2. `git checkout shared-bundle-assetpath`
3. `npm i && bower i`
4. `gulp build`
5. `npm start`

You can also see deployed site live [here](https://sandbox-e0d4b.firebaseapp.com/demo/first/).

P. S. poor `gold-cc-cvc-input`, how much it suffered - and maybe our users too, at least I would thinks twice before entering any credentials if I saw such a broken input 😞

**Comment by usergenic** [comment]
Looking at the generated file `./dist/src/components/shards/bundle-2.html`, I see the assetpath on `gold-cc-cvc-input` and it looks correct to me...
```html
    <dom-module id="gold-cc-cvc-input" assetpath="../../../vendor/gold-cc-cvc-input/">
```
But you're right, the src attribute is not being rewritten in the template:
```html
<iron-icon
              id="icon" src="cvc_hint.png" hidden$="[[_amex]]" alt="cvc"></iron-icon>
```
There was a breaking change mentioned [2.0.0-pre.12 CHANGELOG](https://github.com/Polymer/polymer-bundler/blob/master/CHANGELOG.md#200-pre12---2017-04-14) which disables rewriting of element attributes in templates to support the new Polymer 2 way, where element authors would rewrite it as:
```html
<iron-icon
              id="icon" src$="[[importPath]]cvc_hint.png" hidden$="[[_amex]]" alt="cvc"></iron-icon>
```

The good news is, there's a setting in Bundler to turn on the old behavior.  So just modify your `bundler()` options in your gulpfile:
```js
.pipe(project.bundler({
        rewriteUrlsInTemplates: true,
        strategy: bundler.generateShellMergeStrategy(polymerJSON.shell, 3),
        urlMapper: bundler.generateCountingSharedBundleUrlMapper('src/components/shards/bundle-')
      }))
```

Then it will generate:
```html
            <iron-icon
              id="icon" src="../../../vendor/gold-cc-cvc-input/cvc_hint.png" hidden$="[[_amex]]" alt="cvc"></iron-icon>
```

Which looks right to me, but the `dist` folder doesn't include that path-- I don't know enough about that, except to say, that bundler itself is not responsible for that...

Maybe I'm missing something but at least this bundler option fixes the html for you and you got the rest?

**Comment by web-padawan** [comment]
Hmm, thanks. I forgot to copy that icon. Just updated the sandbox and deployed the site demonstrating that rewriting works (you might need to clear cache in order to see changes). 
Shame on me, didn't realize the sense of that BREAKING change (although have read the Changelog).
