### ISSUE TITLE
Lazy Imports not getting resolved correctly in bundles

### ISSUE THREAD

**Issue by stramel** [Polymer/polymer-bundler#504]
**Steps to Reproduce:**

1. Clone https://github.com/jay8t6/lazy-import-bundle
2. Run `npm i;bower i`
3. Run `npm run build`
4. Run `polymer serve build/ -o`
5. Open console

**Expected Result:** `paper-button` will lazily import into the side bar

**Actual Result:** `paper-button` doesn't import. You can see in the console that the import failed and resolved to `bower_components/bower_components/paper-button/paper-button.html`

@usergenic

**Comment by usergenic** [comment]
Added a failing test to prove the behavior in https://github.com/Polymer/polymer-bundler/tree/lazy-import-href-resolution-investigation
```
  1) Bundler lazy imports are treated like entrypoints:
     AssertionError: The href of the lazy import link in the inlined dom-module should not be modified: expected '<div hidden="" by-polymer-bundler=""><link rel="import" href="../shared_bundle_1.html"><l
ink rel="import" href="shared-eager-and-lazy-import-1.html"><dom-module id="eager-import-1" assetpath="subfolder/">\n  <link type="lazy-import" href="subfolder/lazy-import-3.html">\n  <script>\n    conso
le.log(\'eager-import-1\');\n  </script>\n</dom-module>\n</div><div id="lazy-import-2">\n  I am lazy import 2\n</div>\n' to include '<link rel="lazy-import" href="lazy-import-3.html">'
```

Updating bundler code to stop monkeying with hrefs inside dom-modules that have been inlined.

A little concerned this issue might be related to more than just lazy imports.  I don't know if assetpath is honored for any urls other than lazy ones, but keeping an eye out for them.

Anyways, hopefully will have a reasonably straightforward fix for this in a moment.
