### ISSUE TITLE
[question] Is hidden div required for bundles not containing html?

### ISSUE THREAD

**Issue by web-padawan** [Polymer/polymer-bundler#507]
In our project we have special imports used to de-duplicate libraries like `d3` and `ace` and to put them to shared bundles. After using crisper, our bundle looks like this:
```html
<html>

<head></head>

<body>
    <div hidden="" by-polymer-bundler=""></div>
    <script src="bundle-7.js"></script>
</body>

</html>
```
That empty `div` used to contain one `script` tag before running `crisper`.
Can we just remove that div in those cases? Should bundler catch this or not?

**Comment by usergenic** [comment]
I'm all for bundler removing the hidden div if it's empty.  Great idea.

**Comment by web-padawan** [comment]
Actually this div only becomes empty after extracting script tag. Maybe it would be enough to check that bundle contains nothing but inlined scripts.
