### ISSUE TITLE
Lazy Import Bundling

### ISSUE THREAD

**Issue by stramel** [Polymer/polymer-bundler#511]
I'm wondering if there is a better way to handle lazy-imports with bundling other than requiring that they all be fragments. Please bear with me, this is kinda half-baked lol

Bundle each group of lazy-imports into their own bundle with the exception of; a single import in the group, imports that are included in fragments, and imports that show up in multiple places, which would be treated as implied fragments. These lazy-import links, which make up the bundle, would be replaced with the bundled href.

Again, this was just something I thought of and thought it might be cool to implement. Let me know what you think! @usergenic 

PSA: Copious amounts of partial code examples

### Single Import
**Before:**
```html
<dom-module id="my-app">
    <link rel="lazy-import" group="view1" href="my-view1.html">
    <link rel="lazy-import" group="view2" href="my-view2.html">
```
**After:**
```html
<dom-module id="my-app">
    <link rel="lazy-import" group="view1" href="my-view1.html">
    <link rel="lazy-import" group="view2" href="my-view2.html">
```

### Multiple Imports
**Before:**
```html
<dom-module id="my-app">
    <link rel="lazy-import" group="lazy" href="component-1.html">
    <link rel="lazy-import" group="lazy" href="component-2.html">
```
**After:**
```html
<dom-module id="my-app">
    <link rel="lazy-import" group="lazy" href="lazy-bundled-components.html">
```

### Multiple Imports with Fragment
**Before:**
```json
{
  "fragments": [
    "components-1.html"
  ]
}
```
```html
<dom-module id="my-app">
    <link rel="lazy-import" group="lazy" href="component-1.html">
    <link rel="lazy-import" group="lazy" href="component-2.html">
```
**After:**
```html
<dom-module id="my-app">
    <link rel="lazy-import" group="lazy" href="component-1.html">
    <link rel="lazy-import" group="lazy" href="component-2.html">
```

### Multiple Imports with same import in another file
```html
<dom-module id="my-app">
    <link rel="lazy-import" group="lazy" href="component-1.html">
    <link rel="lazy-import" group="lazy" href="component-2.html">
```
```html
<dom-module id="view1">
    <link rel="lazy-import" group="lazy" href="component-2.html">
```
**After:**
```html
<dom-module id="my-app">
    <link rel="lazy-import" group="lazy" href="component-1.html">
    <link rel="lazy-import" group="lazy" href="component-2.html">
```
```html
<dom-module id="view1">
    <link rel="lazy-import" group="lazy" href="component-2.html">
```

or with enough to bundle

**Before:**
```html
<dom-module id="my-app">
    <link rel="lazy-import" group="lazy" href="component-1.html">
    <link rel="lazy-import" group="lazy" href="component-2.html">
    <link rel="lazy-import" group="lazy" href="component-4.html">
```
```html
<dom-module id="view1">
    <link rel="lazy-import" group="lazy" href="component-2.html">
```
**After:**
```html
<dom-module id="my-app">
    <link rel="lazy-import" group="lazy" href="lazy-bundled-components.html">
    <link rel="lazy-import" group="lazy" href="component-2.html">
```
```html
<dom-module id="view1">
    <link rel="lazy-import" group="lazy" href="component-2.html">
```

**Comment by usergenic** [comment]
@stramel I do like the idea of bundling lazy imports together that are part of the same group and are exclusive to that group.  Seems like a cool optimization, thought I wonder how frequently that scenario appears in the wild?

**Comment by usergenic** [comment]
One additional caveat, wrt to the last example, is that the order of the imports changes if you bundle component-1 and component-4 together and then load component-2.  That might violate the expectation of someone who constructed their code (even unintentionally) to be order-dependent.

We try very hard to preserve the execution order of imports in the bundler, though in the case of lazy imports that's probably something that might need to be more relaxed anyways.

**Comment by stramel** [comment]
wrt import order, that is a good point that I didn't think about.

Another thing to keep in mind that we also support `:not([group])` as a "group" of lazy-imports. 

Thank you for the feedback, it would be interesting to know how often this kind of optimization could be applied. I will try to keep an eye out locally but I'm not sure how to get more detail about it.

**Comment by stramel** [comment]
I'm going to go ahead and close this. With P3 moving towards ES Modules, lazy-imports will be going away.
