### ISSUE TITLE
URLs in inlined stylesheets are rewritten incorrectly when they refer out of the build root

### ISSUE THREAD

**Issue by vlukashov** [Polymer/polymer-bundler#531]
When polymer-bundler inlines styles with URLs (e.g. background images or fonts), the URLs referring to the resources outside of the build root are rewritten incorrectly.

**Example:**
With the following folder structure:
```
webapp/frontend/styles.css
webapp/frontend/index.html
webapp/images/icon.svg
```

Run the polymer-bundler in the webapp/frontend folder:
```
$ cd webapp/frontend
$ polymer-bundler index.html
```

See that in the output HTML the URL from the styles.css is incorrectly rewritten to `images/icon.svg` whereas the URL in the inline style block remained correct (`../images/icon.svg`)

index.html:
```html
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="styles.css">
  <title>Unbundled Resource</title>
</head>
<body>
<style type="text/css">
  .from-style-in-doc-body {
    background: url(../images/icon.svg);
  }
</style>
</body>
</html>
```

styles.css:
```css
.from-style-in-linked-css {
  background: url(../images/icon.svg);
}
```

polymer-bundler output:
```html
<!DOCTYPE html><html lang="en"><head>
  <meta charset="UTF-8">
  <style>.from-style-in-linked-css {
  background: url("images/icon.svg");
}
</style>
  <title>Unbundled Resource</title>
</head>
<body>
<style type="text/css">
  .from-style-in-doc-body {
    background: url(../images/icon.svg);
  }
</style>
</body></html>
```

**Rationale for using resources from outside of the build root:**
We build and ship several versions of the frontend code (es5 and es6) inside our deployment package. While the JS / HTML bundles are different in each build, the static resources (like fonts and images) are the same. In order to avoid duplicating that static content, we keep them out of the build root and reference with relative URLs from the files within the build root.

**Comment by vlukashov** [comment]
Would you accept a PR fixing this issue?

**Comment by usergenic** [comment]
Interesting.  We definitely want to support hrefs for assets outside the package root, so I'm labeling this a bug.  If you have already have a patch, definitely submit a PR.   In any event, I'll label and prioritize.
