### ISSUE TITLE
Excludes option should honor js and css assets in addition to html imports

### ISSUE THREAD

**Issue by usergenic** [Polymer/polymer-bundler#548]
The `excludes` option appears to only apply to html imports and folders containing those imports.  It needs to honor js and css assets as well.

**Comment by usergenic** [comment]
@freshp86

**Comment by micschro** [comment]
Isn't this a duplicate of #530?

**Comment by usergenic** [comment]
Yep, duplicate of https://github.com/Polymer/polymer-bundler/issues/530
