### ISSUE TITLE
Output not wrapped in <html><head>...</head><body>...</body></html>

### ISSUE THREAD

**Issue by freshp86** [Polymer/polymer-bundler#555]
This is a difference I noticed while trying to migrate from Vulcanize to polymer-bundler in Chromium. It specifically causes an issue because we are [manually injecting](https://cs.chromium.org/chromium/src/chrome/browser/resources/vulcanize_gn.py?q=vulcanize_gn.py&sq=package:chromium&dr&l=156-159) a `<base>` tag inside the `<head>` after vulcanize runs.

Repro steps: Place the following line inside `foo.html`
```html
<div>hello</div>
```
Executing vulcanize as follows
```
node node_modules/vulcanize/bin/vulcanize foo.html
```
outputs
```html
<html><head><meta charset="UTF-8"></head><body><div>Hello</div>
</body></html>
```

Equivalent command in polymer-bundler
```
node_modules/polymer-bundler/lib/bin/polymer-bundler.js foo.html
```
outputs
```
<div>Hello</div>
```

cc @usergenic @danbeam

**Comment by stramel** [comment]
@freshp86 what are you trying to achieve by injecting the base tag into the head?

**Comment by usergenic** [comment]
We opted to not add these root elements when missing from original documents as a matter of choice to preserve fidelity.  Is there an observed issue with builds that do not contains the added elements?

**Comment by usergenic** [comment]
If foo html has head tag it will be preserved.  Suggest updating foo?

**Comment by freshp86** [comment]
@stramel: Previously with vulcanize we observed that it was eating [our `<base>` tags](https://cs.chromium.org/chromium/src/chrome/browser/resources/settings/settings.html?l=7) (`<base>` tag appearing in input would not appear in output). The reason we need the `<base>` tag in the first place is a bit unique to our case, given that Chromium's Settings page can be served via two different domains (for now), chrome://settings and chrome://md-settings, so we needed to preserve the `<base>` tag and dynamically populate it with the currently used domain.

@usergenic: Let me try that. If it works then I am OK with it.

**Comment by freshp86** [comment]
@usergenic: Modifying the HTML file on our side seems to work fine. Closing for now.
