### ISSUE TITLE
--out-dir is ignored if only one --in-html is provided

### ISSUE THREAD

**Issue by freshp86** [Polymer/polymer-bundler#560]
Minimal repro: Put the following contents in bug.html

```html
<div>Hello bug.html</div>
```

Then execute
```
node node_modules/polymer-bundler/lib/bin/polymer-bundler.js --in-html bug.html --out-dir foo/
```

The output is thrown in stdout, and no `foo/` folder is created. If a 2nd HTML file is passed with `--in-html` the output folder is created and stdout is empty as expected.

**Comment by freshp86** [comment]
cc @usergenic

**Comment by freshp86** [comment]
Related code seems to be at https://github.com/Polymer/polymer-bundler/blob/master/src/bin/polymer-bundler.ts#L282-L299.

**Comment by freshp86** [comment]
Should this be marked as fixed?

**Comment by usergenic** [comment]
Yep.  Closing.  Fixed.
