### ISSUE TITLE
Feature Request: async imports

### ISSUE THREAD

**Issue by nicholaswmin** [Polymer/polymer-bundler#565]
Would be very nice if we could declare an import as `async`/`defer` when bundling. Is that possible?

##  A potential (but unworkable) 'workaround'

Create 2 bundles:

  - `elements.html`.
  - `elements-async.html`. 

And import one with `async`:

`<link rel="import" href="elements.html"/>`
`<link rel="import" href="elements-async.html" async/>`

## Why this won't work

The problem is that there's gonna be dependencies in one bundle that potentially exist in the other bundle and thus they won't be properly deduped.

Which of course, will lead to `DOM registration failed.. An element with that name already exists` errors.

## Ideally

Of course ideally, the bundler should preserve the `async` tag negating the need for hacks like the one described above.

**Comment by usergenic** [comment]
Neither `async` nor `defer` are a part of the spec for `<link>` tags, so I think if these were to be supported by bundler at all, they really should have a polyfill/implementation that fulfills their intent client-side for the non-bundled case.  I'm reticent to explore this in light of our overarching premise of #UseThePlatform -- However, to better understand the value proposition etc, I'll give this a shot:

`async` and `defer` each add different kind of dimensions to the bundling problem, if their behavior would be analogous to the same attributes currently implemented on `<script>` tag.

For `async`, the intent is "definitely load this, but I don't care when; don't block anything else".  If a particular import is ONLY ever `async` imported, then it becomes a candidate to bundle along with its exclusive dependencies or with other `async`-only imports and their exclusive and shared dependencies.  The win would be the production of a hopefully non-blocking smaller bundle of core dependencies or two tiers of bundles: one set of eager 

In the case of `defer`, this is an explicit instruction for the browser to not execute imperatives in the import until after the full page parse, so this becomes a specific re-ordering declaration and could basically be handled by the bundler by shuffling the link tag around to the end of the page and most everything would continue to work as defined.

All this is a little bit moot though if the client wouldn't obey the same rules of engagement.  Our goal with bundler is that the various web clients out there will eventually not need bundling, with server push etc allowing multiple assets to be delivered within in a single `request -> response`.

Would recommend exploring `lazy-import` for your needs as it captures some aspects of what you want with async and you could achieve similar effect of `async` by triggering an immediate `lazyImportGroup` on page load.

**Comment by usergenic** [comment]
@nicholaswmin https://github.com/Polymer/lazy-imports
