### ISSUE TITLE
Output a flattened dependency list for users with h2

### ISSUE THREAD

**Issue by jpodwys** [Polymer/polymer-bundler#566]
I would really love if this tool could output a single file with all nested `<link rel="import"...` references throughout a given project, but not the code referenced by those imports. This would be extremely useful for users who already enjoy http/2, but want to eliminate head-of-line blocking. It seems this tool already does more than what I'm asking for. Would it be feasible to augment this tool to output all import lines rather than the code those imports reference?

Thank you!

**Comment by usergenic** [comment]
@jpodwys can you give a concrete example of what you mean?  I can't tell if you're saying you want essentially a transitive dependency list for entrypoints to the import graph or something else.

There is a `--manifest-out` option for the `bin/polymer-bundler.js` CLI tool that, given a path to write it out to, like `bundle-manifest.json` will generate a file that shows you all of the urls which are inlined into each bundle.  This seems like the information you want?  *Unfortunately* to generate that file right now requires performing the bundling.  There's no `--dry-run` option right now for bundler; perhaps if we added one that would be more like what you want?

Also, bundler supports not inlining css and scripts (just give `{inlineScripts: false, inlineCss: false}` to the constructor...)

Let me know if the `--manifest-out` option helps you or if I can offer direction on how to use the bundler code programmatically to achieve what you want.  Mostly though, would love to understand exactly what kind of artifact you would find most useful.

**Comment by jpodwys** [comment]
I apologize if I simply didn't read the docs well enough. The `--manifest-out` option is probably what I want.

As an example of what I'm hoping for, say that I have the following dependency tree:

my-el
-- paper-bogus
----- paper-bogus-behavior
-- iron-something
----- iron-something-behavior
-- other-el
---- other-el-behavior
---- grand-child
------ great-grand-child

I would expect a file that outputs the following flattened import list as only URLs or as complete link rel imports (except with correct relative paths) as follows:

```html
<link rel="import" href="my-el/my-el.html">
<link rel="import" href="paper-bogus/paper-bogus.html">
<link rel="import" href="paper-bogus-behavior/paper-bogus-behavior.html">
<link rel="import" href="iron-something/iron-something.html">
<link rel="import" href="iron-something-behavior/iron-something-behvaior.html">
<link rel="import" href="other-el/other-el.html">
<link rel="import" href="other-el-behavior/other-el-behavior.html">
<link rel="import" href="grand-child/grand-child.html">
<link rel="import" href="great-grand-child/great-grand-child.html">
```

Is this what `--manifest-out` already does?

**Comment by usergenic** [comment]
The `--manifest-out` option is a minimal serialization of the bundle result that is basically a big map of `bundle url -> [inlined import 1, inlined import 2, inlined import 3, ...etc]`.

One doesn't typically bundle a single `my-el`, unless `my-el` in this case was a `fragment` of your application or the shell or something.  Lets say it was, then your manifest out would look like:

```json
{
  "my-el/my-el.html": [
    "my-el/my-el.html",
    "paper-bogus/paper-bogus-behavior.html",
    "iron-something/iron-something.html",
    "iron-something/iron-something-behavior.html",
    "other-el/other-el.html",
    "other-el/other-el-behavior.html",
    "grand-child/grand-child.html",
    "gread-grand-child/great-grand-child.html"
  ]
}
```
The code that generates it is here https://github.com/Polymer/polymer-bundler/blob/master/src/bin/polymer-bundler.ts#L232 fwiw

**Comment by jpodwys** [comment]
Thanks!
