### ISSUE TITLE
polymer-bundler silently ignores imports/scripts it can't find

### ISSUE THREAD

**Issue by freshp86** [Polymer/polymer-bundler#574]
This is different than Vulcanize's behavior, and it seems that it can cause problems that are not immediately detected.

Repro steps: Put the following contents in a file called `silent_ignore.html`
```html
<link rel="import" href="does_not_exist.html">
<script src="does_not_exist.js"></script>
<div>hello world</div>
```

Executing vulcanize returns an error (as expected).
```
> node node_modules/vulcanize/bin/vulcanize silent_ignore.html 
```
```
ERROR finding /tmp/temp/does_not_exist.js
{ Error: ENOENT: no such file or directory, open '/tmp/temp/does_not_exist.js'
    at Error (native)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/tmp/temp/does_not_exist.js' }
```

On the other hand, executing polymer-bundler silently ignores the missing files and succeeds.
```
> node node_modules/polymer-bundler/lib/bin/polymer-bundler.js silent_ignore.html
```
```
<div hidden="" by-polymer-bundler=""><link rel="import" href="does_not_exist.html"><script src="does_not_exist.js"></script></div><div>hello world</div>
```

cc @usergenic

**Comment by usergenic** [comment]
Bundler doesn't really have any error-output regimen.  We can do two things possibly:

 - Emit missing import warnings to stderr
 - Possibly provide an option to fail / exit early with code > 0 on missing import

**Comment by freshp86** [comment]
Maybe a 3rd option be to list all the missing references in some section of the output manifest. Either way, I think the 2nd approach you are mentioning would be preferable over throwing warnings in stderr while returning a success error code.

**Comment by freshp86** [comment]
Thanks, I am about to try this shortly.

**Comment by usergenic** [comment]
Since we are able to identify the missing imports now by reviewing the bundle manifest, I'm going to mark this issue as closed.
