### ISSUE TITLE
vulcanize 1.x - reverses inlined style order inside dom-module

### ISSUE THREAD

**Issue by usergenic** [Polymer/polymer-bundler#575]
The styles are prepended, but when there's more than one, that effectively reverses their sequence.
https://github.com/Polymer/polymer-bundler/blob/1.x/lib/vulcan.js#L404

Possibly as simple as reversing the order this collection is iterated over: https://github.com/Polymer/polymer-bundler/blob/1.x/lib/vulcan.js#L369

This effects users stuck on vulcanize 1.x only

**Comment by azakus** [comment]
@usergenic It looks like `_moveDomModuleStyleIntoTemplate` in master has the same logic bug.

**Comment by azakus** [comment]
Fixed with #577 in 1.x and #578 in master.
