### ISSUE TITLE
root dependency missing from manifest-out output

### ISSUE THREAD

**Issue by freshp86** [Polymer/polymer-bundler#592]
/cc @usergenic 
Minimal example below

Contents of a.html
```html
<link rel="import" href="c.html">
<div>Hello a.html</div>
```

Contents of b.html
```html
<link rel="import" href="c.html">
<div>hello b.html</div>
```

Contents of c.html
```html
<div>Hello c.html</div>
```

Execute the following command
```
node node_modules/polymer-bundler/lib/bin/polymer-bundler.js --manifest-out manifest.json --out-dir tmp_out_dir --shell a.html --in-html a.html --in-html b.html
```

Inspecting the contents of `manifest.json` reveals that a.html is missing as a dependency.
```
{"b.html":["b.html"],"a.html":["c.html"]}
```
Expected
```
{"b.html":["b.html"],"a.html":["a.html", "c.html"]}
```

**Comment by usergenic** [comment]
https://github.com/Polymer/polymer-bundler/pull/593 should fix this.  Sending for review.

**Comment by usergenic** [comment]
polymer-bundler 3.0.1 published 🎉 with this fix
