### ISSUE TITLE
Bundler adds source html as html import

### ISSUE THREAD

**Issue by dkirchhof** [Polymer/polymer-bundler#596]
Hello,
while testing a bundled polymer app i got many errors like this one:
> Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry

...but with my source files everything is working fine.   
So i inspected the bundled html and found out that it imports the source html ("index.html") at the end of the body tag.  
To reproduce it, i made a small, quite empty html file without any imports and bundled it. This is the result:

deleteme.html:
```html
<!DOCTYPE html>
<html>
<head>
</head>
<body>
</body>
</html>
```
bundle.html:
```html
<!DOCTYPE html><html><head>
</head>
<body>

<link rel="import" href="deleteme.html"></body></html>
```
execute polymer bundler:
```powershell
# polymer-bundler: 3.0.1
polymer-bundler.cmd deleteme.html > bundle.html
```

Obviously i will get the errors because the browser will load my bundled and unbundled html file. So all polymer dependecies and custom components will be parsed twice.

**Comment by onwarion** [comment]
+1
In my case the import results in a GET request to the server for /index.html, which results in a 404 error since the page is a SPA and the server doesn't have a route to service such requests.
Is there a workaround?

**Comment by usergenic** [comment]
unable to reproduce your experience with example `deleteme.html` and 3.0.1 polymer-bundler.  with what OS and version of node are you encountering this issue?

**Comment by usergenic** [comment]
@dkirchhof @onwarion ^

**Comment by onwarion** [comment]
Can't help much since I moved to native components, but this is what I have from my repo:
OS : Windows 10
polymer.json : 
```
{
  "entrypoint": "index.html",
  "builds": [{
    "bundle": true,
    "inlineScripts": "true",
    "js": {"minify": true},
    "css": {"minify": true},
    "html": {"minify": true}
  }]
}
```
Build folder polymer.json : 
```
{
  "entrypoint": "index.html",
  "fragments": [],
  "sources": [
    "src\\**\\*",
    "index.html"
  ],
  "extraDependencies": [
    "bower_components\\webcomponentsjs\\*.js"
  ],
  "builds": [
    {
      "bundle": true,
      "inlineScripts": "true",
      "js": {
        "minify": true
      },
      "css": {
        "minify": true
      },
      "html": {
        "minify": true
      }
    }
  ]
}
```
The insert is ".......<link rel="import" href="index.html"></body></html>" at the end of the bundle.

**Comment by usergenic** [comment]
I think i've found a way to reproduce on mac.   its a path comparison thing.  i am writing test to prove its fixed.  thanks for replying!

**Comment by usergenic** [comment]
Will get this released in next point release of bundler.
