### ISSUE TITLE
Bundled components with external stylesheets

### ISSUE THREAD

**Issue by felixzapata** [Polymer/polymer-bundler#599]
hi @usergenic

I have some components with legacy code that [use the deprecated system to import stylesheets](https://www.polymer-project.org/1.0/docs/devguide/styling#external-stylesheets). For some reasons I' ve had to change to the `polymer build` who uses under the hoods the `polymer-bundler`.

The problem is when I build a bundled of all my application, these stylesheets are not included in the `head` when you run the application. 

The support for this deprecated system was removed in a previous version of the polymer-bundler or it never was added?

Thanks

**Comment by usergenic** [comment]
@felixzapata would you say this is same issue as https://github.com/Polymer/polymer-bundler/issues/600 for you?

**Comment by felixzapata** [comment]
oops, yes.. it is the same, sorry.

**Comment by usergenic** [comment]
no oops.  i think you filed yours first :)
