### ISSUE TITLE
Bundler is not inlining css when the <link> is inside the <template>

### ISSUE THREAD

**Issue by ergo** [Polymer/polymer-bundler#600]
Bundler is not inlining css when the <link> element is enclosed by the <template> tags.

Following repository contains reproductible test case:

https://github.com/ergo/polymer-build-inlining-bug

When building shared-styles file https://github.com/ergo/polymer-build-inlining-bug/blob/master/src/shared-styles.html#L15 if `<link rel="stylesheet" href="shared-styles.css">` is enclosed by `<template>` then build output does not contained inlined styles, removal of the tag results in correct behavior.

When using old `vulcanize` approach the assets were inlined correctly.

**Comment by rictic** [comment]
Specifically this is a style module that references an external stylesheet, i.e. 

```html
<dom-module id="shared-styles">
  <template>
      <link rel="stylesheet" href="shared-styles.css">
  </template>
</dom-module>
```

It seems like we should inline the following into the toplevel document:

```html
<dom-module id="shared-styles">
  <template>
    <style>
      /* content of shared-styles.css here */
    </style>
  </template>
</dom-module>
```

**Comment by ergo** [comment]
That is correct and this was what `vulcanize` did in the past.

**Comment by usergenic** [comment]
Marking this as a bug because bundler is trying to have feature parity with vulcanize and this behavior is crucial to support bundling for stylesheets authored outside the template.  Prioritizing.

**Comment by ergo** [comment]
Hello, are there any news on this?

**Comment by usergenic** [comment]
@ergo soon!  I am working on some other pressing issues but I am hoping to get back on this by end of week or start of next week.  Thanks for your patience
