### ISSUE TITLE
polymer-bundler run error on mips64el platform

### ISSUE THREAD

**Issue by ClarkWang-2013** [Polymer/polymer-bundler#602]
polymer-bundler version:3.0.1
OS: fedora21
ARCH: mips64el 

when run polymer-bundler occurs error as follows:
 
/usr/lib/node_modules/polymer-bundler/lib/bin/polymer-bundler.js:178
        const [prefix, path] = redirect.split('|');
              ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3

**Comment by usergenic** [comment]
what version of node are you running?  we are targeting 6+

**Comment by ClarkWang-2013** [comment]
node -v
v4.3.1

**Comment by usergenic** [comment]
That sounds like the problem.  Bundler no longer supports running on node 4 as it is not longer on Node's own LTS schedule.  We dropped support around the same time they did, in April 2017.

This is node's own schedule, which determines supported versions; we honor their LTS schedule as our own baseline of support.
https://github.com/nodejs/Release#release-schedule1

**Comment by usergenic** [comment]
Specifically, the error is that node 4 doesn't support the destructuring assignment feature:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

But there are several other ways Node 4 doesn't support code in bundler and its polymer-analyzer dependency, so please try to upgrade Node to v6 or v8.
