### ISSUE TITLE
JavaScript module support

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polymer-bundler#612]
We currently don't bundle JavaScript, only inline it. We'll need to support bundling script for modules.

- [x] Add support for modules to Analyzer.
    - Full module support is tracked here: https://github.com/Polymer/polymer-analyzer/issues/731
    - Import support was added in https://github.com/Polymer/polymer-analyzer/pull/732 and https://github.com/Polymer/polymer-analyzer/pull/733
    - Dynamic import support is tracked here: https://github.com/Polymer/polymer-analyzer/issues/740
- [ ] Track JavaScript files in the bundle manifest
- [ ] Generate lists of JS files to bundle.
- [ ] Generate bundles - whether we write new code to do this or delegate to Rollup is TBD. We're going to experiment with Rollup first.
- [ ] Rewrite references to bundled files.

**Comment by rjsteinert** [comment]
I believe a lot of the Angular community was using Rollup, but standardized on Webpack as implemented in the Angular CLI.

Examples of bundling polymer 3 with webpack:
- https://github.com/chybie/poly-mini-game
- https://github.com/pferretti/polymer3-typescript

**Comment by craftyc0der** [comment]
Is there any documentation available for bundling a Polymer 3 app for Firefox/Edge?

**Comment by rjsteinert** [comment]
@craftyc0der I work on a [project that currently uses Webpack bundle Polymer 3](https://github.com/Tangerine-Community/Tangerine/tree/v3/client/tangy-forms). Not much for documentation but it's an example. Unfortunately it's also not the cleanest example as we are Webpack n00bs.

**Comment by justinfagnani** [comment]
FYI, we're using Rollup in the Bundler. The PRs are being reviewed now. We'll have documentation soon.

**Comment by usergenic** [comment]
This is in master now.
